package org.orderpaymentsystem.common.enums;

public enum ErrorEnums {
	ORDER_NOT_FOUND,
	ORDER_ALREADY_CANCELLED,
	ORDER_CANNOT_BE_MODIFIED,
	PAYMENT_NOT_FOUND,
	DUPLICATE_PAYMENT,
	INVALID_ORDER_STATE,
	PAYMENT_CANNOT_BE_RETRIED,
	CANCELLED_ORDER_CANNOT_BE_MODIFIED,
	ORDER_NOT_FOUND_FOR_PAYMENT,
	PAYMENT_CANNOT_BE_CANCELLED,
	INTERNAL_SERVER_ERROR,
	VALIDATION_FAILED
}
