spring.application.name=api-gateway

server.port=8080
spring.cloud.gateway.server.webmvc.routes[0].id=identity
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/eshop/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/eshop/auth/(?<suburl>.*), /auth/api/${suburl}


spring.cloud.gateway.server.webmvc.routes[1].id=catalog
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/eshop/products/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/eshop/products(?<suburl>/.*)?, /products/api${suburl}

spring.cloud.gateway.server.webmvc.routes[2].id=basket
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/eshop/basket/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/eshop/basket(?<suburl>/.*)?, /basket/api${suburl}

spring.cloud.gateway.server.webmvc.routes[3].id=order
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/eshop/orders/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/eshop/orders(?<suburl>/.*)?, /orders/api${suburl}

spring.cloud.gateway.server.webmvc.routes[4].id=payment
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/eshop/payments/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/eshop/payments(?<suburl>/.*)?, /payments/api${suburl}


jwt.secret=4HfMIUIYdVwdnZJXHhLrPAMp2NJmoIUipkAFyCsjqCc=

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.servlet.function=TRACE