spring.application.name=orderpaymentsystem
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/orderdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
