spring:
    application:
        name: basket-service
    profiles:
        active: local
    config:
        import: configserver:http://localhost:8888
    http:
        serviceclient:
            catalog-service:
                connect-timeout: 3s
                read-timeout: 10s

server:
    port: 8084

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

logging:
    level:
        "[org.springframework.web.client]": DEBUG
        "[org.springframework.web.service]": DEBUG
        "[org.springframework.cloud.loadbalancer]": DEBUG
        "[com.netflix.discovery]": DEBUG
        "[org.springframework.cloud.netflix.eureka]": DEBUG
