spring:
    application:
        name: basket-service
    profiles:
        active: local
    config:
        import: configserver:http://localhost:8888
    http:
        serviceclient:
            catalog-service:
                connect-timeout: 3s
                read-timeout: 15s

    cloud:
        circuitbreaker:
            http-services:
                enabled: false
resilience4j:
    retry:
        instances:
            catalogService:
                maxAttempts: 3
                waitDuration: 1s
                retryExceptions:
                    - org.springframework.web.client.HttpServerErrorException
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 3
                permittedNumberOfCallsInHalfOpenState: 3
                waitDurationInOpenState: 10s
                failureRateThreshold: 50
        instances:
            catalogService:
                baseConfig: default

management:
    endpoints:
        web:
            exposure:
                include: health,metrics
server:
    port: 8084

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
logging:
    level:
        "[io.github.resilience4j.circuitbreaker]": DEBUG
