package io.github.codecraft87.eshop.common.enums;

public enum ErrorEnums {
     BASKET_NOT_FOUND, PAYMENT_CANNOT_BE_RETRIED, PRODUCT_NOT_FOUND, PAYMENT_CANNOT_BE_CANCELLED, INTERNAL_SERVER_ERROR, VALIDATION_FAILED, RESOURCE_NOT_FOUND, REGISTRATION_FAILED
}
